### ISSUE TITLE
How to use ReadStruct function?

### ISSUE THREAD

**Issue by kennythum** [brkp/SLMP#1]
Greetings! I'm having some trouble regarding the ReadStruct function, could you kindly please provide some example of it? I've define a structure and call the function into it, but how do we access the data inside the structure? Thank you very much.

**Comment by seg6** [comment]
Hello! The `ReadStruct` function is defined as follows:
```
public T? ReadStruct<T>(string addr) where T : struct;
```

which means that it returns a value of type `T` on success. Here's a complete example:

```C#
public struct ExampleStruct {
    public bool boolean_word;              // 2 bytes, 1 word
    public int signed_double_word;         // 4 bytes, 2 words
    public uint unsigned_double_word;      // 4 bytes, 2 words
    public short short_signed_word;        // 2 bytes, 1 word
    public ushort ushort_unsigned_word;    // 2 bytes, 1 word
    [SlmpString(length = 6)]
    public string even_length_string;      // 6 bytes, 3 words (there's an extra 0x0000 right after the string in the plc memory)
    [SlmpString(length = 5)]
    public string odd_length_string;       // 5 bytes, 3 words (upper byte of the 3rd word is 0x00)
}

ExampleStruct? data = plc.ReadStruct<ExampleStruct>("D200");
// or
ExampleStruct? data = plc.ReadStruct<ExampleStruct>(Device.D, 200);

// access its fields
Console.WriteLine(data!.even_length_string);
```

Make sure that you fully understand the layout of data that this library will parse as it is not configurable at the moment. Feel free to ask more questions if something isn't clear.

**Comment by kennythum** [comment]
Thank you very much! I will try it as soon once I've get the device!

**Comment by seg6** [comment]
Closing this as it's stale, feel free to re-open it if you've anything to ask.
